### ISSUE TITLE
Implement password encryption

### ISSUE THREAD

**Issue by Vyvy-vi** [SamDev98/password-manager-py#13]
Currently, it seems that the passwords are stored in csv files as plaintext.
Implementing some version of encryption would be great.
You could look into hashing the main user password(Irreversible encryption. You check encrypt the password entry and check it against the stored encrypted version) and reversible encryption for the entire db with a key. (I would suggest, look into something that allows no access to the files or something like that)

Sources:
https://docs.python-guide.org/scenarios/crypto/
https://pypi.org/project/pycrypto/

**Comment by SamDev98** [comment]
Thanks for reporting! Yes, this enhancement is already underway. The master password is being used as the encryption key for now. I will push my changes to a branch and you can review them there.

**Comment by SamDev98** [comment]
Thank you again for reporting this issue, I have added the file encryption feature. Will close the issue once the PR is merged.

**Comment by SamDev98** [comment]
Thanks for your contribution! @all-contributors please add @Vyvy-vi  for ideas
