### ISSUE TITLE
Feature: [To-Do] Web based UI

### ISSUE THREAD

**Issue by SamDev98** [SamDev98/password-manager-py#21]
**Is your feature request related to a problem? Please describe.**
A web-based UI for the application 💻 

**Describe the solution you'd like**
Implementation of web UI pages to supply the application with a web interface.
The backend for this project is ready to ship. 🚀

**Comment by BrendaMichellle** [comment]
You can assign me to the issue. Also if you have more specifics of what you would like for the front end would be helpful. Thanks

**Comment by SamDev98** [comment]
@BrendaMichellle Sure, thank you for taking this up :) The tasks are the same as discussed with you previously. Once we have atleast one page ready as per the UI template i shared, we can take it from there.

**Comment by SamDev98** [comment]
@BrendaMichellle Thank you for your contribution.
